import {
  FaUniversity,
  FaChalkboardTeacher,
  FaTrain,
  FaShieldAlt,
  FaUserShield,
  FaHospital,
  FaLandmark,
  FaFileAlt,
} from 'react-icons/fa'

export const examCategories = [
  { id: 'banking', name: 'Banking Assessments', icon: FaUniversity, color: '#2f8bf0' },
  { id: 'teaching', name: 'Teaching Assessments', icon: FaChalkboardTeacher, color: '#f59e0b' },
  { id: 'civil', name: 'Civil Services Assessment', icon: FaLandmark, color: '#8b5cf6' },
  { id: 'railways', name: 'Railways Assessments', icon: FaTrain, color: '#ef4444' },
  { id: 'engineering', name: 'Engineering Recruitment Assessments', icon: FaUniversity, color: '#0ea5e9' },
  { id: 'defence', name: 'Defence Assessments', icon: FaShieldAlt, color: '#10b981' },
  { id: 'state', name: 'State Govt. Assessments', icon: FaLandmark, color: '#d946ef' },
  { id: 'police', name: 'Police Assessments', icon: FaUserShield, color: '#14b8a6' },
  { id: 'insurance', name: 'Insurance Assessments', icon: FaShieldAlt, color: '#64748b' },
  { id: 'nursing', name: 'Nursing Assessments', icon: FaHospital, color: '#ff5c8a' },
  { id: 'other', name: 'Other Govt. Assessments', icon: FaFileAlt, color: '#7c5cfc' },
]

export const exams = [
  { id: 1, name: 'IBPS RRB Clerk', category: 'banking' },
  { id: 2, name: 'IBPS RRB PO', category: 'banking' },
  { id: 3, name: 'SBI PO', category: 'banking' },
  { id: 4, name: 'IBPS SO', category: 'banking' },
  { id: 5, name: 'RBI Assistant', category: 'banking' },
  { id: 6, name: 'HARCO Bank Clerk', category: 'banking' },
  { id: 7, name: 'PNB LBO', category: 'banking' },
  { id: 8, name: 'NABARD Development', category: 'banking' },
  { id: 9, name: 'RBI Office Attendant', category: 'banking' },
  { id: 10, name: 'RBI Grade B', category: 'banking' },
  { id: 11, name: 'Sangli DCC Bank Clerk', category: 'banking' },
  { id: 12, name: 'Bihar State Cooperative', category: 'banking' },
  { id: 13, name: 'Bank of India PO', category: 'banking' },
  { id: 14, name: 'Bank of Baroda LBO', category: 'banking' },
  { id: 15, name: 'SBI CBO', category: 'banking' },
  { id: 16, name: 'MP Apex Bank', category: 'banking' },
  { id: 17, name: 'HDFC Bank PO', category: 'banking' },
  { id: 18, name: 'MP Apex Bank Society', category: 'banking' },
  { id: 19, name: 'APCOB Staff Assistant', category: 'banking' },
  { id: 20, name: 'Union Bank LBO', category: 'banking' },
  { id: 21, name: 'Bank of Baroda PO', category: 'banking' },
  { id: 22, name: 'JAIIB Assessment', category: 'banking' },
  { id: 23, name: 'UP Cooperative Bank', category: 'banking' },
  { id: 24, name: 'Federal Bank Officer', category: 'banking' },
  { id: 25, name: 'CTET', category: 'teaching' },
  { id: 26, name: 'UPTET', category: 'teaching' },
  { id: 27, name: 'REET', category: 'teaching' },
  { id: 28, name: 'HTET', category: 'teaching' },
  { id: 29, name: 'DSSSB PRT', category: 'teaching' },
  { id: 30, name: 'KVS TGT', category: 'teaching' },
  { id: 31, name: 'UPSC IAS', category: 'civil' },
  { id: 32, name: 'UPSC CDS', category: 'civil' },
  { id: 33, name: 'UPSC EPFO', category: 'civil' },
  { id: 34, name: 'MPSC', category: 'civil' },
  { id: 35, name: 'RRB NTPC', category: 'railways' },
  { id: 36, name: 'RRB Group D', category: 'railways' },
  { id: 37, name: 'RRB JE', category: 'railways' },
  { id: 38, name: 'RRB ALP', category: 'railways' },
  { id: 39, name: 'SSC JE', category: 'engineering' },
  { id: 40, name: 'ISRO Scientist', category: 'engineering' },
  { id: 41, name: 'ONGC Assessment', category: 'engineering' },
  { id: 42, name: 'BHEL Assessment', category: 'engineering' },
  { id: 43, name: 'NDA', category: 'defence' },
  { id: 44, name: 'AFCAT', category: 'defence' },
  { id: 45, name: 'Agniveer', category: 'defence' },
  { id: 46, name: 'ACC Assessment', category: 'defence' },
  { id: 47, name: 'SSC CHSL', category: 'state' },
  { id: 48, name: 'UPPSC', category: 'state' },
  { id: 49, name: 'TNPSC', category: 'state' },
  { id: 50, name: 'WBCS', category: 'state' },
  { id: 51, name: 'Delhi Police Constable', category: 'police' },
  { id: 52, name: 'CISF Assessment', category: 'police' },
  { id: 53, name: 'CRPF Assessment', category: 'police' },
  { id: 54, name: 'Sub Inspector', category: 'police' },
  { id: 55, name: 'LIC AAO', category: 'insurance' },
  { id: 56, name: 'LIC ADO', category: 'insurance' },
  { id: 57, name: 'NICL AO', category: 'insurance' },
  { id: 58, name: 'GIC Assistant', category: 'insurance' },
  { id: 59, name: 'NORCET', category: 'nursing' },
  { id: 60, name: 'MNS Assessment', category: 'nursing' },
  { id: 61, name: 'CHO Assessment', category: 'nursing' },
  { id: 62, name: 'Staff Nurse Assessment', category: 'nursing' },
  { id: 63, name: 'SSC MTS', category: 'other' },
  { id: 64, name: 'SSC GD', category: 'other' },
  { id: 65, name: 'FCI Assessment', category: 'other' },
  { id: 66, name: 'CWC Assessment', category: 'other' },
]
