# Generated by Django 6.0.8 on 2026-08-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('instructor', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('ONE_TIME', 'One-time')], default='ONE_TIME', max_length=20)),
                ('mrp', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('pass_fees', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('scorm', 'SCORM'), ('file', 'File'), ('heading', 'Heading'), ('text', 'Text'), ('link', 'Link'), ('quiz', 'Quiz'), ('livetest', 'Live test'), ('liveclass', 'Live class'), ('assignment', 'Assignment'), ('coding', 'Coding test'), ('form', 'Form')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='items/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.coursechapter')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
