# Generated by Django 6.0.8 on 2026-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='file',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='file_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
