# Generated by Django 6.0.7 on 2026-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courseitem_file_courseitem_file_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='quiz_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
