# Generated by Django 6.0.8 on 2026-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseitem_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_bookmarks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='canonical_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='offline_usage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='show_curriculum_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='show_validity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tax_rate',
            field=models.CharField(blank=True, default='18', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_email_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_email_subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
